const { app, BrowserWindow, ipcMain } = require('electron');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const output = path.join(root, 'artifacts/ui');
fs.mkdirSync(output, { recursive: true });
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'deck-ui-'));
app.setPath('userData', profile);
app.whenReady().then(async () => {
  const themeBundle = path.join(profile, 'themes.cjs');
  require('esbuild').buildSync({ entryPoints: [path.join(root, 'src/shared/themes.ts')], outfile: themeBundle, bundle: true, platform: 'node', format: 'cjs' });
  const { builtInThemes, parseTheme } = require(themeBundle);
  const pluginRoot = path.join(root, 'examples/plugins/workspace-kit');
  const manifest = JSON.parse(fs.readFileSync(path.join(pluginRoot, 'deck-plugin.json'), 'utf8'));
  const pluginTheme = { ...parseTheme(JSON.parse(fs.readFileSync(path.join(pluginRoot, 'ocean.json'), 'utf8'))), id: 'workspace-kit:ocean', source: manifest.name };
  const plugin = { ...manifest, path: pluginRoot, enabled: true, source: fs.readFileSync(path.join(pluginRoot, 'index.js'), 'utf8'), themes: [pluginTheme] };
  const customThemes = [];
  ipcMain.handle('test:catalog', () => ({ themes: [...builtInThemes, ...customThemes, ...(plugin.enabled ? [pluginTheme] : [])], plugins: [{ ...plugin, source: plugin.enabled ? plugin.source : undefined, themes: plugin.enabled ? plugin.themes : [] }], errors: [], themesDirectory: profile, pluginsDirectory: profile }));
  ipcMain.handle('test:enable', (_event, enabled) => { plugin.enabled = enabled; });
  ipcMain.handle('test:save-theme', (_event, input) => { const theme = { ...parseTheme(input), id: 'custom:' + input.id, source: 'Custom' }; customThemes.push(theme); return theme; });
  const window = new BrowserWindow({ width: 1440, height: 900, show: false, webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true }, backgroundColor: '#080808' });
  const errors = [];
  window.webContents.on('console-message', (event) => { if (event.level === 'error') errors.push(event.message); });
  await window.loadFile(path.join(root, 'out/renderer/index.html'));
  const run = (script) => window.webContents.executeJavaScript(script);
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const screenshot = async (name) => { await wait(200); fs.writeFileSync(path.join(output, name + '.png'), (await window.webContents.capturePage()).toPNG()); };
  const click = async (label) => {
    const found = await run(`(() => { const button = [...document.querySelectorAll('button,[role=button]')].find(button => button.getAttribute('aria-label') === ${JSON.stringify(label)} || button.title === ${JSON.stringify(label)} || button.textContent.trim() === ${JSON.stringify(label)}); if (!button) return false; button.click(); return true; })()`);
    if (!found) throw Error('Missing control: ' + label);
    await wait(150);
  };
  const visiblePanes = () => run(`[...document.querySelectorAll('.xterm')].filter(element => element.offsetWidth > 0).length`);
  await wait(800);
  await click('Build a better terminal (Codex)');
  await screenshot('normal');
  await click('Split right');
  if (await visiblePanes() !== 2) throw Error('Split did not show two panes');
  await screenshot('split');
  await click('File explorer');
  if (!(await run(`document.body.innerText.includes('package.json')`))) throw Error('File explorer failed');
  await screenshot('files');
  await click('Close file explorer');
  await click('Zen view');
  if (!(await run(`document.querySelector('[data-display-mode="zen"]') && document.querySelector('aside').offsetWidth === 0`))) throw Error('Zen did not hide chrome');
  if (await visiblePanes() !== 1) throw Error('Zen should focus one pane');
  await screenshot('zen');
  await click('Exit zen view');
  if (await visiblePanes() !== 2) throw Error('Leaving Zen did not restore split');
  await click('Build a better terminal (Codex)');
  await click('Presentation view');
  if (await visiblePanes() !== 1) throw Error('Presentation should focus one pane');
  await screenshot('presentation');
  await click('Larger presentation text');
  if (!(await run(`document.body.innerText.includes('22px')`))) throw Error('Presentation font control failed');
  await click('Next presentation session');
  await click('Previous presentation session');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape',bubbles:true,cancelable:true}))`);
  await wait(150);
  if (!(await run(`document.querySelector('[data-display-mode="normal"]')`))) throw Error('Escape did not exit presentation');
  await click('Toggle sidebar');
  if (await run(`Boolean(document.querySelector('aside'))`)) throw Error('Sidebar did not collapse');
  await click('Toggle sidebar');
  await click('New session');
  await click('New Codex');
  if (!(await run(`document.body.innerText.includes('Codex')`))) throw Error('Codex launch absent');
  await click('Settings');
  await screenshot('themes');
  await click('Use Paper theme');
  if (await run(`document.documentElement.dataset.theme`) !== 'light') throw Error('Theme did not apply');
  await click('terminal');
  await screenshot('light');
  await click('Settings');
  await click('Customize');
  await run(`(() => { const input = document.querySelector('textarea[aria-label="Custom theme JSON"]'); const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set; setter.call(input, JSON.stringify({id:'ui-custom',name:'UI Custom',extends:'forest',colors:{accent:'#abcd12'}})); input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await click('Preview');
  if (await run(`document.documentElement.dataset.theme`) !== 'ui-custom') throw Error('Custom theme preview failed');
  await click('Save theme');
  if (await run(`document.documentElement.dataset.theme`) !== 'custom:ui-custom') throw Error('Custom theme save failed');
  await click('Plugins');
  await click('Workspace overview');
  if (!(await run(`document.body.innerText.includes('Stay in flow')`))) throw Error('Worker plugin panel failed');
  await screenshot('plugin-panel');
  await click('Close plugin panel');
  await click('Switch to Ocean');
  if (await run(`document.documentElement.dataset.theme`) !== 'workspace-kit:ocean') throw Error('Plugin theme command failed');
  await screenshot('plugins');
  await run(`document.querySelector('input[aria-label="Enable Workspace Kit"]').click()`);
  await wait(200);
  if (await run(`[...document.querySelectorAll('button')].some(button => button.textContent.includes('Workspace overview'))`)) throw Error('Disabled plugin retained commands');
  await run(`document.querySelector('input[aria-label="Enable Workspace Kit"]').click()`);
  await wait(400);
  await click('Review workspace with Codex');
  if (!(await run(`document.body.innerText.includes('Codex')`))) throw Error('Plugin Codex launch failed');
  await click('Settings');
  await click('Appearance');
  await click('Use Carbon theme');
  await click('terminal');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'k',metaKey:true,bubbles:true,cancelable:true}))`);
  await wait(150);
  await run(`(() => { const input = document.querySelector('input[aria-label="Search Deck"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'terminal'); input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await wait(500);
  await click('Codex conversation');
  if (!(await run(`document.body.innerText.includes('A saved Codex conversation')`))) throw Error('Codex history preview failed');
  await screenshot('history');
  await click('Resume in terminal →');
  const resumed = await run(`window.deck.term.list()`);
  if (!resumed.some(term => term.agent === 'codex' && term.sessionId === 'codex:history')) throw Error('Codex history resume failed');
  await require('./sidebar.cjs')({ window, run, click, wait, screenshot });
  await click('agents');
  await click('Which of my Jira tasks are in review?');
  if (!(await run(`[...document.querySelectorAll('.md')].some(element => element.innerText.includes('Ready'))`))) throw Error('Ask Deck did not render its completed answer');
  if (errors.length) throw Error(errors.join('\n'));
  console.log('UI smoke passed: focus, splits, files, Zen, Presentation, font sizing, session navigation, Escape, sidebar, Codex launch, themes, custom preview/save, plugin worker panel, plugin themes, disable/enable agent command, Codex history preview and resume, recent suggestions, expiry, dismissal, search and close all.');
  window.destroy();
  app.quit();
}).catch((error) => { console.error(error); app.exit(1); });
setTimeout(() => { console.error('UI smoke timed out'); app.exit(1); }, 45000).unref();
